### ISSUE TITLE
Support Enter/Shift/Ctrl keys

### ISSUE THREAD

**Issue by Vdragon** [joezeng/endless-sans#1]
As title, support the alternate Undertale keyboard control to skip message and continue

**Comment by Kampfkarren** [comment]
Which keys do what?

**Comment by Vdragon** [comment]
![undertale exe - wine desktop_012](https://cloud.githubusercontent.com/assets/1192163/11171182/941d06d8-8c24-11e5-9b11-7bdd33e64d6c.png)
Enter to continue
Shift to skip message

**Comment by resir014** [comment]
@Vdragon Unfortunately, the `threex.keyboardstate` library doesnt seem to support Enter key handling. Though the code does have the Space key as an alternative (seen [here](https://github.com/joezeng/endless-sans/blob/master/js/input.js#L42)).
