### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by Thetechie15** [joezeng/endless-sans#11]
![2016-01-22](https://cloud.githubusercontent.com/assets/14289448/12518467/a5b10450-c0ed-11e5-8729-2f83dbad1200.png)
The bones don't show up in any of the difficulties.

**Comment by joezeng** [comment]
Can you check your dev console for me? Right-click anywhere and click "Inspect".

**Comment by Thetechie15** [comment]
![2016-01-22 1](https://cloud.githubusercontent.com/assets/14289448/12518573/4408d5b0-c0ee-11e5-9e4f-825227c70af2.png)

**Comment by Thetechie15** [comment]
It works on Firefox, not chrome

**Comment by joezeng** [comment]
Hmm, that explains it. You're trying to access the game locally. You need to run a node http-server in order to do it properly — Chrome won't allow you to access file:/// URLs due to cross-origin browser request restrictions.

**Comment by Thetechie15** [comment]
Cool. Thanks m8. Awesome simulator though. Keep up the good work :+1:
