### ISSUE TITLE
Found a very annoying bug

### ISSUE THREAD

**Issue by whamer100** [joezeng/endless-sans#6]
When playing on my android phone, it wont load past the Sans gif. I use puffin browser so i can use an emulated controller

**Comment by joezeng** [comment]
I downloaded Puffin to try it and got the same problem. I'll have to look into whether Puffin has some sort of weird Javascript hack that makes it not load properly, because it has the same problem with all my apps that use Three.js whereas it works fine on mobile Chrome.

**Comment by joezeng** [comment]
I checked and Puffin Browser doesn't seem to support WebGL by default, which is the reason the game won't load in 90% of cases. Unfortunately there's not much I can do about that.
