### ISSUE TITLE
Using the Determination font instead of 8-bit Operator?

### ISSUE THREAD

**Issue by Roadcrosser** [joezeng/endless-sans#7]
Someone [made a font](https://www.behance.net/gallery/31268855/Determination-Better-Undertale-Font) to closely follow that used by the game.

I think it'd be better than using 8-bit Operator.

**Comment by joezeng** [comment]
My variation of 8-bit Operator dealt with the problems the Plus font has. (The original font was also a variation of 8-bit Operator called "8-bit Operator JVE", and I adjusted the letters of my font to fit _that_ one".)
