### ISSUE TITLE
Game doesn't start in Google Chrome

### ISSUE THREAD

**Issue by fernyettheplant** [joezeng/endless-sans#8]
i was triying to play this game the other day and i took the surprise that this game doesn't "work" in chrome. the game "freezes" right here (See attachment 1)
![stuck](https://cloud.githubusercontent.com/assets/3887243/11669237/eeaa56fa-9db8-11e5-910f-eb4309e59158.PNG) Attachment 1

i took a look in the developer console and it throws the next exceptions (See attachment 2)
![errors](https://cloud.githubusercontent.com/assets/3887243/11669280/20c15a76-9db9-11e5-988b-48fb2762f109.PNG) Attachment 2

and finally when im tapping any key it throws the next error (See attachment 3)
![rootscene](https://cloud.githubusercontent.com/assets/3887243/11669301/3b00b9c2-9db9-11e5-8ba4-e5022e45e6a6.PNG) Attachment 3

**Comment by joezeng** [comment]
Your version of Chrome doesn't have WebGL enabled. Check [here](http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser) for instructions on how to enable it.
