### ISSUE TITLE
Player can survive at 0.00/1 health

### ISSUE THREAD

**Issue by Samario1** [joezeng/endless-sans#9]
It is possible in rare instances for the player to be left on 0.00/1 HP but still be able to play.
![image](http://i.imgur.com/4QdmOpf.png)

**Comment by joezeng** [comment]
Oh, that's because the decimal rounding sometimes makes the HP go below 0.005. I could change the code for it, but it might be rather complex.

**Comment by joezeng** [comment]
Turns out it wasn't as complex as I thought.

Closed via https://github.com/joezeng/endless-sans/commit/1b58ef50796bd877bb15178f0b6c947e8fc9e612.
